# Generated by Django 3.1 on 2020-11-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_auto_20201114_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='crmapp.company')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='crmapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='friends',
            field=models.ManyToManyField(related_name='_company_friends_+', through='crmapp.Friendship', to='crmapp.Company'),
        ),
    ]
