# Generated by Django 3.1 on 2020-11-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_auto_20201116_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='friends',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CompanyFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crmapp.company')),
            ],
        ),
    ]
