# Generated by Django 3.1 on 2020-11-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_auto_20201116_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='friends',
            field=models.ManyToManyField(through='crmapp.Friendship', to='crmapp.Company'),
        ),
    ]
