# Generated by Django 3.1 on 2020-11-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_auto_20201116_0351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyFriend',
        ),
    ]
